=== Byounes123321/XML-DTD/books-XLM/books.dtd
<!ELEMENT books (book*)>
<!ELEMENT book (ISBN, Title, Year, Lang, Author)>

<!ATTLIST book  
    id CDATA #REQUIRED
>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Year (#PCDATA)>
<!ELEMENT Lang (#PCDATA)>
<!ELEMENT Author (#PCDATA)>

=== Byounes123321/XML-DTD/books-XLM/books.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE books SYSTEM "books.dtd">

<books>
    <book id="1">
        <ISBN>16979819798</ISBN>
        <Title>Lord of The Rings: The Fellowship of the Ring</Title>
        <Year>1954</Year>
        <Lang>EN</Lang>
        <Author>J.R.R. Tolkien</Author>
    </book>
    <book id= "2">
        <ISBN>98156465462</ISBN>
        <Title>Lord of The Rings: The Two Towers</Title>
        <Year>1955</Year>
        <Lang>EN</Lang>
        <Author>J.R.R. Tolkien</Author>
    </book>
</books>
